
ERASED, VALID, INVALID = 'ERASED', 'VALID', 'INVALID'
PAGE_PROGRAMMED, PAGE_ERASED = 'PAGE_PROGRAMMED', 'PAGE_ERASED'

BYTE, KB, MB, GB, TB = [2**(10*i) for i in range(5)]

# unit is based on nanoseconds
SEC, MSEC, USEC, NSEC = [ 1000**3, 1000*2, 1000*1, 1 ]

